wandb_version: 1

T:
  desc: null
  value: 0.5
_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.6
alpha:
  desc: null
  value: 0.75
batch_size:
  desc: null
  value: 64
class_num:
  desc: null
  value: 10
dropout:
  desc: null
  value: 0.4
ema_decay:
  desc: null
  value: 0.999
epoch:
  desc: null
  value: 1024
experiment:
  desc: null
  value: 1224_Bayes_drop_0_4
gpu_device:
  desc: null
  value: 0
lambda_u:
  desc: null
  value: 75
learning_rate:
  desc: null
  value: 0.002
n_labeled:
  desc: null
  value: 250
seed:
  desc: null
  value: 1
train_iteration:
  desc: null
  value: 1024
weight_decay:
  desc: null
  value: 0.0004
