wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
batch_size:
  desc: null
  value: 64
epoch:
  desc: null
  value: 1024
experiment:
  desc: null
  value: 1218_normal
gpu_device:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.002
n_labeled:
  desc: null
  value: 250
seed:
  desc: null
  value: 1
train_iteration:
  desc: null
  value: 1024
weight_decay:
  desc: null
  value: 0.0004
